# Generated by Django 4.2.4 on 2023-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='barcode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='distance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sale',
            field=models.TextField(null=True),
        ),
    ]
