# Generated by Django 4.2.4 on 2023-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shop_address_alter_shop_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.TextField()),
                ('name', models.TextField()),
                ('website', models.TextField()),
                ('sale', models.TextField(null=True)),
                ('price', models.TextField()),
                ('barcode', models.TextField()),
            ],
        ),
    ]
