# Generated by Django 4.2.3 on 2023-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('sale', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
            ],
        ),
    ]
