# Generated by Django 4.2.4 on 2023-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.TextField()),
                ('name', models.TextField()),
                ('website', models.TextField()),
                ('sale', models.TextField(null=True)),
                ('price', models.TextField()),
                ('barcode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('distance', models.TextField()),
                ('sale', models.TextField(null=True)),
                ('price', models.TextField()),
                ('barcode', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
