# Generated by Django 4.2.3 on 2023-08-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_onlineshop_shop_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('unix_time', models.DateTimeField(max_length=20)),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='chain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='sale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='distance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sale',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
