# Generated by Django 4.2.3 on 2023-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_message_unix_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
